<a href="https://colab.research.google.com/github/SupidchayaTangkidwanich/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

# Numpy Array

## สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 เเถว 3 หลัก สร้าง matrix จาก list

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape # เช็คขนาด (เเถว,หลัก)

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros,ones)

In [9]:
np_z = np.zeros((4,5))   # matrix เริ่มต้นคือ matrix ที่กำหนดค่าให้เป็น 0,1
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np_200 = 200 * np.ones((4,7))
np_200 # ทำเป็นค่า 200 ทุกค่าใน matrix เอา 200 * one matrix

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random ค่าเเบบมั่วๆ

In [13]:
np.random.randn(5,5) # randn คือ random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 1.76392526,  0.74012408, -0.94067188,  1.45968064, -1.90364028],
       [-0.08623589,  0.39217289,  0.40681628, -0.17852526, -0.31467939],
       [ 1.07504711, -0.43391517, -1.4896713 ,  1.1093369 , -0.35298415],
       [-1.2749272 ,  0.4269912 ,  0.23324992, -0.02046686,  0.81306796],
       [-0.32153452, -0.45781702, -1.36118808, -0.43487037,  0.29374817]])

In [14]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[15.19151513,  5.7819061 , 10.60703793],
       [ 7.06103853,  3.01555279,  4.93983009],
       [-2.37180466,  0.68347153, -2.0411284 ]])

In [17]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 9,  8,  5,  6,  7],
       [ 6,  9, 10,  5,  7],
       [ 7,  7,  5,  6,  6],
       [ 6,  7,  6,  5,  8]])